const express = require('express')
const app = express()
const PORT = 3000

// Set a strong ETag, 
// If this is commented, a weak ETag will be generated by default.
app.set('etag', 'strong')

app.get('/results', (req, res) => {
  res.status(200).json({
    ok: true
  })
})

app.listen(PORT, () => {
  console.log(`listening to port *:${PORT}. press ctrl + c to cancel.`)
})